package squareoneinsights

case class CsvRecord(partner_id : Option[String],cif : Option[String],aadhar_detail : Option[String],aadhar_hash : Option[String],aadhar_id_flag : Option[String],aadhar_mask: Option[String],address_1 : Option[String],address_2 : Option[String],address_3 : Option[String],alt_mobile_number : Option[String],attribute_1 : Option[String],attribute_2 : Option[String],attribute_3: Option[String],
                     attribute_4 : Option[String],attribute_5 : Option[String],birth_date : Option[String],category : Option[String],city : Option[String],ckyc_number : Option[String],country : Option[String],created_timestamp: Option[String],
                     customer_risk_level : Option[String],customer_type : Option[String],declaration_ckyc_number : Option[String],declaration_last_name : Option[String],declaration_pan: Option[String],
                     din_dpin : Option[String],driving_license_number : Option[String],email : Option[String],employer_district : Option[String],employer_locality : Option[String],employer_name : Option[String],father_name: Option[String],
                     gender : Option[String],income_range : Option[String],is_married : Option[String],is_staff : Option[String],is_urban : Option[String],last_kyc_date : Option[String],last_name : Option[String],latitude : Option[String],loadmoney_card_count: Option[String],
                     longitude : Option[String],loop_type : Option[String],measure_1 : Option[String],measure_2 : Option[String],measure_3 : Option[String],measure_4 : Option[String],measure_5 : Option[String],middle_name : Option[String],mobile_number : Option[String],mother_name: Option[String],
                     name : Option[String],nationality : Option[String],non_resident : Option[String],npr : Option[String],nrega_card : Option[String],occupation : Option[String],other_customer_type : Option[String],other_occupation : Option[String],pan_detail : Option[String],pan_hash: Option[String],
                     pan_mask : Option[String],passport_number : Option[String],pekrn : Option[String],pin_code : Option[String],sec_address1 : Option[String],sec_city : Option[String],sec_country : Option[String],sec_district: Option[String],
                     sec_locality : Option[String],sec_pincode : Option[String],sec_state : Option[String],spouse_name : Option[String],state : Option[String],telephone_number : Option[String],time_1 : Option[String],time_2 : Option[String],time_3 : Option[String],time_4 : Option[String],time_5: Option[String],
                     ucic : Option[String],updated_at : Option[String],updated_timestamp : Option[String],voter_id : Option[String],work_address : Option[String],work_city : Option[String],work_country : Option[String],work_latitude : Option[String],work_longitude: Option[String],
                     work_pin_code : Option[String],work_state: Option[String])
